### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by maneetgoyal** [viki-user/ManuFacAssignment#1]
Hi @viki-user,

1. Can you get rid of all the unused files/code to reduce clutter in the repo?
2. For example, logo.svg, unused CSS etc. can all be removed.
3. We are currently reviewing the code. Will share more feedback soon.

**Comment by maneetgoyal** [comment]
The commenting style can be improved.

Current version:

```
  /* getting the data from csv file --start */
  const reader = res.body.getReader();
  const result = await reader.read();
  const decoder = new TextDecoder("utf-8");
  const csv = decoder.decode(result.value);
  /* getting the data from csv file --end */
```

Can be made:

```
  // #region getting the data from csv file
  const reader = res.body.getReader();
  const result = await reader.read();
  const decoder = new TextDecoder("utf-8");
  const csv = decoder.decode(result.value);
  // #endregion
```

It allows better code folding. (At least in VSCode.)

**Comment by maneetgoyal** [comment]
The source has a mix between `.jsx` and `.tsx` files. Ideally `App.jsx` should also be `App.tsx`.

We made this change and found unresolved TSC errors. Please correct them.

**Comment by maneetgoyal** [comment]
`yarn test` is failing. Either try to fix it or remove test related code and dependencies.

**Comment by viki-user** [comment]
I've fixed all the raised issues.

**Comment by maneetgoyal** [comment]
Thanks, will review again.
